// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Bridge.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface LocationInfo ()
+ (LocationInfo *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation LocationInfo
+ (LocationInfo *)fromMap:(NSDictionary *)dict {
  LocationInfo *result = [[LocationInfo alloc] init];
  result.province = dict[@"province"];
  if ((NSNull *)result.province == [NSNull null]) {
    result.province = nil;
  }
  result.city = dict[@"city"];
  if ((NSNull *)result.city == [NSNull null]) {
    result.city = nil;
  }
  result.distinct = dict[@"distinct"];
  if ((NSNull *)result.distinct == [NSNull null]) {
    result.distinct = nil;
  }
  result.adCode = dict[@"adCode"];
  if ((NSNull *)result.adCode == [NSNull null]) {
    result.adCode = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.province ? self.province : [NSNull null]), @"province", (self.city ? self.city : [NSNull null]), @"city", (self.distinct ? self.distinct : [NSNull null]), @"distinct", (self.adCode ? self.adCode : [NSNull null]), @"adCode", nil];
}
@end

@interface BdLocationHostBridgeCodecReader : FlutterStandardReader
@end
@implementation BdLocationHostBridgeCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [LocationInfo fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface BdLocationHostBridgeCodecWriter : FlutterStandardWriter
@end
@implementation BdLocationHostBridgeCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[LocationInfo class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface BdLocationHostBridgeCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation BdLocationHostBridgeCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[BdLocationHostBridgeCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[BdLocationHostBridgeCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *BdLocationHostBridgeGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    BdLocationHostBridgeCodecReaderWriter *readerWriter = [[BdLocationHostBridgeCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void BdLocationHostBridgeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BdLocationHostBridge> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.BdLocationHostBridge.getLocationInfo"
        binaryMessenger:binaryMessenger
        codec:BdLocationHostBridgeGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getLocationInfoWithCompletion:)], @"BdLocationHostBridge api (%@) doesn't respond to @selector(getLocationInfoWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getLocationInfoWithCompletion:^(LocationInfo *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.BdLocationHostBridge.setIOSKey"
        binaryMessenger:binaryMessenger
        codec:BdLocationHostBridgeGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setIOSKeyKey:error:)], @"BdLocationHostBridge api (%@) doesn't respond to @selector(setIOSKeyKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_key = args[0];
        FlutterError *error;
        [api setIOSKeyKey:arg_key error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
