// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LocationInfo;

@interface LocationInfo : NSObject
@property(nonatomic, copy, nullable) NSString * province;
@property(nonatomic, copy, nullable) NSString * city;
@property(nonatomic, copy, nullable) NSString * distinct;
@property(nonatomic, copy, nullable) NSString * adCode;
@end

/// The codec used by BdLocationHostBridge.
NSObject<FlutterMessageCodec> *BdLocationHostBridgeGetCodec(void);

@protocol BdLocationHostBridge
- (void)getLocationInfoWithCompletion:(void(^)(LocationInfo *_Nullable, FlutterError *_Nullable))completion;
- (void)setIOSKeyKey:(NSString *)key error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BdLocationHostBridgeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BdLocationHostBridge> *_Nullable api);

NS_ASSUME_NONNULL_END
