// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.c1yde3.bd_location;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Brigde {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class LocationInfo {
    private String province;
    public String getProvince() { return province; }
    public void setProvince(String setterArg) { this.province = setterArg; }

    private String city;
    public String getCity() { return city; }
    public void setCity(String setterArg) { this.city = setterArg; }

    private String distinct;
    public String getDistinct() { return distinct; }
    public void setDistinct(String setterArg) { this.distinct = setterArg; }

    private String adCode;
    public String getAdCode() { return adCode; }
    public void setAdCode(String setterArg) { this.adCode = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("province", province);
      toMapResult.put("city", city);
      toMapResult.put("distinct", distinct);
      toMapResult.put("adCode", adCode);
      return toMapResult;
    }
    static LocationInfo fromMap(Map<String, Object> map) {
      LocationInfo fromMapResult = new LocationInfo();
      Object province = map.get("province");
      fromMapResult.province = (String)province;
      Object city = map.get("city");
      fromMapResult.city = (String)city;
      Object distinct = map.get("distinct");
      fromMapResult.distinct = (String)distinct;
      Object adCode = map.get("adCode");
      fromMapResult.adCode = (String)adCode;
      return fromMapResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class BdLocationHostBridgeCodec extends StandardMessageCodec {
    public static final BdLocationHostBridgeCodec INSTANCE = new BdLocationHostBridgeCodec();
    private BdLocationHostBridgeCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return LocationInfo.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof LocationInfo) {
        stream.write(128);
        writeValue(stream, ((LocationInfo) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface BdLocationHostBridge {
    void getLocationInfo(Result<LocationInfo> result);
    void setIOSKey(String key);

    /** The codec used by BdLocationHostBridge. */
    static MessageCodec<Object> getCodec() {
      return BdLocationHostBridgeCodec.INSTANCE;
    }

    /** Sets up an instance of `BdLocationHostBridge` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, BdLocationHostBridge api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.BdLocationHostBridge.getLocationInfo", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              Result<LocationInfo> resultCallback = new Result<LocationInfo>() {
                public void success(LocationInfo result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.getLocationInfo(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.BdLocationHostBridge.setIOSKey", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String keyArg = (String)args.get(0);
              if (keyArg == null) {
                throw new NullPointerException("keyArg unexpectedly null.");
              }
              api.setIOSKey(keyArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
